version: "3.9"
services:
  api_rest: &api
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - rabbitmq_network
    working_dir: /app
    build:
      context: .
    entrypoint: "sh docker-entrypoint.sh"
    command: bin/rails s -b 0.0.0.0 -p 3001
    volumes:
      - .:/app
  postgres:
    image: postgres:12.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "postgres"
    networks:
      - rabbitmq_network
  sidekiq:
    <<: *api
    ports: []
    entrypoint: []
    environment:
      NOAUTH: 1
    links:
      - redis
      - postgres
    command: bundle exec sidekiq -c 1
  sneakers:
    <<: *api
    ports: []
    entrypoint: []
    command: bundle exec rake sneakers:run
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - postgres
      - redis
    networks:
      - rabbitmq_network
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
  redis:
    image: redis
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    name: rabbitmq_network
    external: true