version: "3.9"
services:
  api_rest:
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - rabbitmq
      - redis
    links:
      - postgres
      - rabbitmq
      - redis
    working_dir: /app
    build:
      context: .
    entrypoint: "sh docker-entrypoint.sh"
    volumes:
      - .:/app
  postgres:
    image: postgres:12.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "postgres"
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
  redis:
    image: redis
